# Site
repository: Neuw84/neuw84.github.io
# not usedfavicon: assets/favicon.ico

# Personal info
name: Angel Conde Manjon
title: Ph.D., Data Engineer at Ikerlan & Flow Master
#email: Your email (optional)
website: www.acmanjon.es

# Social links
twitter_username: neuw84
github_username:  neuw84
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: acmanjon
linkedin_username: acmanjon
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/me.jpg
about_content: | # this will include new lines to allow paragraphs here you can use all markdown features!
  I am a technology enthusiast that loves to learn and work with the latest technologies. Currently developing Big Data platforms for the Industry 4.0. at [Ikerlan](https://www.ikerlan.es/).
  
  Technologies that I use everyday:
    * ![SpringBoot](assets/spring-boot-logo.png){:height="33px"}
    * ![Spark](assets/spark-logo-hd.png){:height="40px"} 
    * ![Kafka](assets/kafka_logo.png){:height="36px"}
    * ![Mesos](assets/images.png){:height="30px"}
    * ![Kubernetes](assets/kubernetes-horizontal-color.png){:height="28x"}
    * ![MQTT](assets/MQTT.png){:height="22px"}
    
   Moreover, I like to give talks at conferences (e.g. [Big Data Spain](https://www.bigdataspain.org/)) or meetups (e.g. [DataBeers Eus](https://databeerseus.tumblr.com/)) when I have time &#9786;. The slides of my public talks can be seen at [SlideShare](https://es.slideshare.net/AngelCondeManjon/presentations)
   
   **Research**
   
   Currently, my research interests include: *IA*, *IoT*, *Big Data*, *Cloud* and any kind of *Distributed System*. 
   
   See my [Google Academic](https://scholar.google.es/citations?user=RcnJ168AAAAJ&hl=en) profile.
 
   
# Projects Section
# projects_title: Research #(Use this to override about experience section title)


# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  When I‚Äôm not sat at my desk I am very active and spend most of my time outdoors. I do a lot of sports, such as mountain biking, surfing, hiking, running or snowboarding. 
  
  Apart from doing sports, I like to watch TV series üçø and landscape photography.
  
  
  
  


# Footer
#footer_show_references: true

# Build settings
#theme: modern-resume-theme  
#(Use this is you are hosting your resume yourself)
#remote_theme: sproogen/modern-resume-theme 
#(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Google Analytics
google_analytics: UA-132400196-1

