# Site
repository: Neuw84/neuw84.github.io
favicon: assets/favicon.ico

# Personal info
name: Angel Conde Manjon
title: Data Engineer at Ikerlan & Flow Master
#email: Your email (optional)
website: www.acmanjon.es

# Social links
twitter_username: neuw84
github_username:  neuw84
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: acmanjon
linkedin_username: acmanjon
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/me.jpg
about_content: | # this will include new lines to allow paragraphs here you can use all markdown features!
  Technology enthusiast that love to learn and work with the latest technologies. Currently developing Big Data platforms for the Industry 4.0. at [Ikerlan](www.ikerlan.es) with the latest Open Source technologies.
  
  Technologies that I use everyday:
    * SpringBoot
    * Spark 
    * Kafka
    * Mesos 
    * Kubernetes
    * MQTT
    * AWS
    
   When I find time, I like to give talks in conferences (e.g. [Big Data Spain](https://www.bigdataspain.org/)) or meetups (e.g. [DataBeers Eus](https://databeerseus.tumblr.com/)) &#9786;
   
   **Research**
   
   Currently, my research interests include: *IA*, *IoT*, *Big Data*, *Cloud* and any kind of *Distributed System*. 
   
   See my [Google Academic](https://scholar.google.es/citations?user=RcnJ168AAAAJ&hl=en) profile.
 
   
# Projects Section
# projects_title: Research #(Use this to override about experience section title)


# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  When Iâ€™m not sat at my desk I am very active and spend most of my time outdoors. I do a lot a sports such as mountain biking, surfing, running and snowboarding. 

# Footer
#footer_show_references: true

# Build settings
#theme: modern-resume-theme  
#(Use this is you are hosting your resume yourself)
#remote_theme: sproogen/modern-resume-theme 
#(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Google Analytics
google_analytics: UA-132400196-1

