# Site
repository: Neuw84/neuw84.github.io
# not usedfavicon: assets/favicon.ico

# Personal info
name: Angel Conde Manjon
title: Ph.D., PSA at AWS & Flow Master
#email: Your email (optional)
#website: https://acmanjon.es/

# Social links
twitter_username: neuw84
github_username:  neuw84
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: acmanjon
linkedin_username: acmanjon
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/me.jpg
about_content: | # this will include new lines to allow paragraphs here you can use all markdown features!
  I am a technology enthusiast that loves to learn and work with the latest technologies. I am currently leading the Data Analytics and Artificial Intelligence team at [Ikerlan](https://www.ikerlan.es/).

  Technologies that I use everyday:
  <div class="col-xs-12">
    <div class="col-xs-6 col-md-4 col-lg-4" style="height: 100%;"><img src="assets/spring-boot-logo.png" alt="SpringBoot" style="margin-bottom: 2px; padding: 5px;"></div>
    <div class="col-xs-6 col-md-4 col-lg-4" style="height: 100%;"><img src="assets/spark-logo-hd.png" alt="Spark" style="margin-bottom: 2px; padding: 5px;"></div>
    <div class="col-xs-6 col-md-4 col-lg-4" style="height: 100%;"><img src="assets/kafka_logo.png" alt="Kafka" style="margin-bottom: 2px; padding: 5px;"></div>
    <div class="col-xs-6 col-md-4 col-lg-4" style="height: 100%;"><img src="assets/images.png" alt="Mesos" style="margin-bottom: 2px; padding: 5px;"></div>
    <div class="col-xs-6 col-md-4 col-lg-4" style="height: 100%;"><img src="assets/kubernetes-horizontal-color.png" alt="Kubernetes" style="margin-bottom: 2px; padding: 5px;"></div>
    <div class="col-xs-6 col-md-4 col-lg-4" style="height: 100%;"><img src="assets/MQTT.png" alt="MQTT" style="margin-bottom: 2px; padding: 5px;"></div>
  </div>
    
    
   Moreover, I like to give talks at conferences (e.g. [Big Data Spain](https://www.bigdataspain.org/)) or meetups (e.g. [DataBeers Eus](https://databeerseus.tumblr.com/)) when I have time &#9786;. The slides of my public talks can be seen at [SlideShare](https://es.slideshare.net/AngelCondeManjon/presentations)
   
   **Research**
   
   My research interests include: *IA*, *IoT*, *Big Data*, *Cloud* and any kind of *Distributed System*. 
   
   See my [Google Academic](https://scholar.google.es/citations?user=RcnJ168AAAAJ&hl=en) profile.
      
   *P.h.D. Theses*
  
   * [Mikel Ca√±izo](https://scholar.google.es/citations?user=RCuu9XUAAAAJ&hl=es): Large-Scale Anomaly Detection and Diagnosis on Industrial Heterogeneous Multi-Sensor Systems Using Deep Learning. Thesis co-supervised with the collaboration of [Enrique Onieva](https://scholar.google.es/citations?hl=es&user=2ww8fYYAAAAJ) from the University of Deusto. 2020
   * [Ane Blazquez](https://scholar.google.es/citations?user=rYN6wQcAAAAJ&hl=es&oi=ao): ongoing....
   
   *M.s.C Theses*
   
   * Samuel Camba: Auto ML applied to Industrial scenarios ( University of Oviedo), 2020.
   * Asier Gomez: Applied DevOps to monitor a Big Data platform (International University of La Rioja), 2018.
   * [Julen Balzategui](https://scholar.google.es/citations?user=ZOFmhl8AAAAJ&hl=es&authuser=1&oi=ao): Advanced Image Data Analytics (Mondragon University), 2018.
   * Guillermo Lapuente: Enabling Real-time Data Analytics for IIoT in Multi-Cloud Environments (University of Basque Country), 2017.
      
# Projects Section
# projects_title: Research #(Use this to override about experience section title)


# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  When I‚Äôm not sat at my desk I am very active and spend most of my time outdoors. I do a lot of sports, such as mountain biking, surfing, hiking, running or snowboarding. 
  
  Apart from doing sports, I like to watch TV series üçø and landscape photography.
  
  
  
  


# Footer
#footer_show_references: true

# Build settings
#theme: modern-resume-theme  
#(Use this is you are hosting your resume yourself)
#remote_theme: sproogen/modern-resume-theme 
#(Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Google Analytics
google_analytics: UA-132400196-1

